apiVersion: "v1"
kind: "Service"
metadata:
  name: "flask-hello-world"
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: http # adding for Istio
  selector:
    app: "flask-hello-world"
  type: "LoadBalancer"